# Use an official Python runtime as a parent image
FROM python:3.9-slim-buster

# Set the working directory in the container
WORKDIR /app

# Install system dependencies required for the ODBC driver
RUN apt-get update && apt-get install -y --no-install-recommends \
    unixodbc \
    unixodbc-dev \
    libodbc1 \
    software-properties-common \
    wget \
    && rm -rf /var/lib/apt/lists/*

# Add Microsoft's repository for SQL Server ODBC driver
RUN wget -qO- https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
RUN add-apt-repository "$(wget -qO- https://packages.microsoft.com/config/debian/10/prod.list)"

# Install the ODBC Driver 17 for SQL Server
RUN apt-get update && apt-get install -y --no-install-recommends \
    msodbcsql17 \
    && rm -rf /var/lib/apt/lists/*

# Copy the requirements file into the container
COPY requirements.txt /app/requirements.txt

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of your application code into the container
COPY . /app

# Expose the port your application runs on (Flask default is 5000)
EXPOSE 8050

# Define the command to run your application (Flask, assuming app object is in main.py)
CMD ["python", "main.py"]
